# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e074970afd7e43d53aab206dfaaeb6b6ba2219f647190cedd7fc4a8f985d9fb9884db1efc698387bf6ff4cc1f3f9c9e34bec6a262df3523e02513e89c63a5287

test:
  secret_key_base: c5bc94daabce062d40674c4323f4f4bc6e8d97294bcdfb40717a8578a4ed6bb8807e1f968e4b6bdd4befe652a42ae950cf6d79adcaf5f0548e2df1cbce905b12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
